on:
  pull_request:
    branches:
    - master
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - name: go lint
      run: |
        go get -u golang.org/x/lint/golint
        golint ./...
    - name: go test
      run: go test -v -cover ./...
